// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantityMeasurementRepositoryLayer.Data;

#nullable disable

namespace QuantityMeasurementRepositoryLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementModelLayer.Entities.QuantityMeasurementEntity", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                b.Property<DateTime>("CreatedAt").IsRequired().HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
                b.Property<string>("ErrorDetails").HasColumnType("text");
                b.Property<string>("FirstOperandCategory").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<string>("FirstOperandUnit").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<double?>("FirstOperandValue").HasColumnType("double precision");
                b.Property<string>("FormattedResult").HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<bool>("IsSuccessful").IsRequired().HasColumnType("boolean");
                b.Property<string>("MeasurementId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<int>("OperationType").IsRequired().HasColumnType("integer");
                b.Property<double?>("ResultValue").HasColumnType("double precision");
                b.Property<string>("ResultUnit").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<string>("SecondOperandCategory").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<string>("SecondOperandUnit").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<double?>("SecondOperandValue").HasColumnType("double precision");
                b.Property<string>("SourceOperandCategory").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<string>("SourceOperandUnit").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<double?>("SourceOperandValue").HasColumnType("double precision");
                b.Property<string>("TargetUnit").HasMaxLength(20).HasColumnType("character varying(20)");
                b.HasKey("Id");
                b.HasIndex("MeasurementId").IsUnique();
                b.HasIndex("CreatedAt");
                b.HasIndex("FirstOperandCategory");
                b.HasIndex("IsSuccessful");
                b.HasIndex("OperationType");
                b.ToTable("QuantityMeasurements");
            });

            modelBuilder.Entity("QuantityMeasurementModelLayer.Entities.UserEntity", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                b.Property<DateTime>("CreatedAt").IsRequired().HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<int>("FailedLoginAttempts").IsRequired().HasDefaultValue(0).HasColumnType("integer");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<bool>("IsActive").IsRequired().HasColumnType("boolean");
                b.Property<string>("LastName").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("LockoutEnd").HasColumnType("timestamp with time zone");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasDefaultValue("User").HasColumnType("character varying(50)");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("QuantityMeasurementModelLayer.Entities.RefreshTokenEntity", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                b.Property<DateTime>("CreatedAt").IsRequired().HasColumnType("timestamp with time zone");
                b.Property<string>("CreatedByIp").HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<DateTime>("ExpiresAt").IsRequired().HasColumnType("timestamp with time zone");
                b.Property<string>("ReplacedByToken").HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<DateTime?>("RevokedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("RevokedByIp").HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("Token").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<long>("UserId").IsRequired().HasColumnType("bigint");
                b.HasKey("Id");
                b.HasIndex("ExpiresAt");
                b.HasIndex("RevokedAt");
                b.HasIndex("Token").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("RefreshTokens");
            });

            modelBuilder.Entity("QuantityMeasurementModelLayer.Entities.RefreshTokenEntity", b =>
            {
                b.HasOne("QuantityMeasurementModelLayer.Entities.UserEntity", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
